# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2507ac1b6c3d7c7fcc22cbf6e576be311304dfeb3c3afb40b92d6a79aa6e234d4977c652c58ad59af4bfede344f7a2ca420579af7d8521e1ee94b8a785423812

test:
  secret_key_base: 21ab7b9ac5986975bca8b9a811e6cd97d3f9de4e036bebe144db38738da16d8dd1012d103f0d5fe0b1442d4ec7d3a480a232bde55121b024f37519e591589de2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
